describe("bean_utils.assertion", function()
    dofile("lua_tests/support/env.lua")

    local assertion = require("bean_utils.assertion")

    describe("assert_none", function()
        it("不做任何校验，任何值都通过", function()
            assert.has_no.errors(function()
                assertion.assert_none(nil)
                assertion.assert_none(123)
                assertion.assert_none("hello")
            end)
        end)
    end)

    describe("assert_int32", function()
        it("正确值通过", function()
            assert.has_no.errors(function()
                assertion.assert_int32(0)
                assertion.assert_int32(100)
                assertion.assert_int32(-0x80000000)
                assertion.assert_int32(0x7FFFFFFF)
            end)
        end)

        it("错误范围报错", function()
            assert.has_error(function()
                assertion.assert_int32(-0x80000001)
            end, "value must be an integer in range [-0x80000000, 0x7FFFFFFF]")
            assert.has_error(function()
                assertion.assert_int32(0x80000000)
            end, "value must be an integer in range [-0x80000000, 0x7FFFFFFF]")
        end)

        it("非整数报错", function()
            assert.has_error(function()
                assertion.assert_int32(1.5)
            end, "value must be an integer in range [-0x80000000, 0x7FFFFFFF]")
            assert.has_error(function()
                assertion.assert_int32("hello")
            end, "value must be an integer in range [-0x80000000, 0x7FFFFFFF]")
        end)
    end)

    describe("assert_uint32", function()
        it("正确值通过", function()
            assert.has_no.errors(function()
                assertion.assert_uint32(0)
                assertion.assert_uint32(100)
                assertion.assert_uint32(0xFFFFFFFF)
            end)
        end)

        it("负数报错", function()
            assert.has_error(function()
                assertion.assert_uint32(-1)
            end, "value must be an integer in range [0, 0xFFFFFFFF]")
        end)

        it("超出范围报错", function()
            assert.has_error(function()
                assertion.assert_uint32(0x100000000)
            end, "value must be an integer in range [0, 0xFFFFFFFF]")
        end)
    end)

    describe("assert_string", function()
        it("正确值通过", function()
            assert.has_no.errors(function()
                assertion.assert_string("hello")
                assertion.assert_string("")
            end)
        end)

        it("非字符串报错", function()
            assert.has_error(function()
                assertion.assert_string(123)
            end, "value must be a string")
            assert.has_error(function()
                assertion.assert_string(nil)
            end, "value must be a string")
        end)
    end)

    describe("assert_boolean", function()
        it("正确值通过", function()
            assert.has_no.errors(function()
                assertion.assert_boolean(true)
                assertion.assert_boolean(false)
            end)
        end)

        it("非布尔报错", function()
            assert.has_error(function()
                assertion.assert_boolean(1)
            end, "value must be a boolean")
            assert.has_error(function()
                assertion.assert_boolean("true")
            end, "value must be a boolean")
            assert.has_error(function()
                assertion.assert_boolean(nil)
            end, "value must be a boolean")
        end)
    end)

    describe("assert_float", function()
        it("正确值通过", function()
            assert.has_no.errors(function()
                assertion.assert_float(1.5)
                assertion.assert_float(0)
                assertion.assert_float(-3.14)
                assertion.assert_float(1 / 0)
            end)
        end)

        it("非数字报错", function()
            assert.has_error(function()
                assertion.assert_float("1.5")
            end, "value must be a number")
            assert.has_error(function()
                assertion.assert_float(nil)
            end, "value must be a number")
            assert.has_error(function()
                assertion.assert_float(true)
            end, "value must be a number")
        end)
    end)
end)
